import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Paper from "@mui/material/Paper";
import { Button, Stack, Typography } from "@mui/material";
import Input from "@mui/material/Input";
import styles from "styles/Home.module.css";
import FileUpload from "components/FileUpload";

const Home: NextPage = () => {
  const [file, setFile] = useState<File>();
  console.log(file);
  return (
    <div className={styles.container}>
      <Head>
        <title>Image Serializer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <FileUpload />
      </main>
    </div>
  );
};

export default Home;
