import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.css";
import FileUpload from "components/FileUpload";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Image Serializer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <FileUpload />
      </main>
    </div>
  );
};

export default Home;
